name: Check License Lines
on: [push, pull_request]
jobs:
  check-license-lines:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@master
      - name: Check License Lines
        uses: kt3k/license_checker@v1.0.6
